// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGoHNe-hrMdgJXilep0ARNLWsFqTItjcw',
    appId: '1:690307246563:web:450052abe3075b588858d6',
    messagingSenderId: '690307246563',
    projectId: 'kkabiheoli-a5eec',
    authDomain: 'kkabiheoli-a5eec.firebaseapp.com',
    storageBucket: 'kkabiheoli-a5eec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM4XI-0iL4DxlUOq98LC5lM67jOH21bF0',
    appId: '1:690307246563:android:b51bd836a8056b4b8858d6',
    messagingSenderId: '690307246563',
    projectId: 'kkabiheoli-a5eec',
    storageBucket: 'kkabiheoli-a5eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR7aAZ7cBicVvclvQcGA0tFUiAb3XyWcQ',
    appId: '1:690307246563:ios:1b9943c99b0118cd8858d6',
    messagingSenderId: '690307246563',
    projectId: 'kkabiheoli-a5eec',
    storageBucket: 'kkabiheoli-a5eec.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
